### ISSUE TITLE
Travis CI 배포 자동화 설정

### ISSUE THREAD

**Issue by suhyunsim** [SimLeeTag/photo-tag-backend#25]
# CI/CD

> 참고: 스프링 부트와 AWS로 혼자 구현하는 웹 서비스 - 이동욱

- 코드 버전 관리를 하는 VCS 시스템에 push가 되면 자동으로 테스트와 빌드가 수행되어 안정적인 배포 파일을 만드는 과정: CI(Continuous Integration - 지속적 통합)
- 빌드 결과를 자동으로 운영 서버에 무중단 배포까지 진행하는 과정: CD(Continuous Deployment - 지속적 배포)
- CI 도구를 도입했다고 해서 CI를 하고 있는 것은 아님 - 4가지 규칙
    - 모든 소스 코드가 살아있고(현재 실행되고) 누구든 현재의 소스에 접근할 수 있는 단일 지점을 유지할 것
    - 빌드 프로세스를 자동화해서 누구든 소스로부터 시스템을 빌드하는 단일 명령어를 사용할 수 있게 할 것
    - **테스팅을 자동화**해서 단일 명령어로 언제든지 시스템에 대한 건전한 테스트 수트를 실행할 수 있게 할 것
    - 누구나 현재 실행 파일을 얻으면 지금까지 **가장 완전한 실행 파일**을 얻었다는 확신을 하게 할 것

---

## Travis CI 연동

- Travis
    - Github에서 제공하는 무료 CI 서비스
- 저장소 활성화
- `build.gradle` 같은 위치에 `.travis.yml` 생성 후 코드 추가

```yaml
language: java
jdk:
  - openjdk8

branches:
  only:
    - dev

# Travis CI 서버의 Homecache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.gradle'

script: "./gradlew clean build -x test"

# CI 실행 완료 시 메일로 알람notifications:
  email:
    recipients:
      - ****@gmail.com

```
- branches: Travis가 어떤 브랜치가 푸시될 때 수행할 지 지정
- cache: gradle을 통해 의존성을 받게 되면 이를 해당 디렉토리에 캐시하며, 같은 의존성은 다음 배포 때부터 다시 받지 않도록 설정
- script: dev 브랜치가 푸시되었을 때 수행하는 명령 (master 브랜치여야 함)
- notification: Travis CI 실행 완료 시 자동으로 알람이 가도록 설정

**배포 흐름**
    ![https://user-images.githubusercontent.com/58318786/103171592-dc184280-4890-11eb-9a5d-cf062ef18742.jpg](https://user-images.githubusercontent.com/58318786/103171592-dc184280-4890-11eb-9a5d-cf062ef18742.jpg)

---

****AWS S3 - Travis CI 연동****

- 실제 배포는 AWS CodeDeploy라는 서비스를 이용하지만 Jar 파일 전달을 위해 S3 연동이 먼저 필요
- CodeDeploy는 저장 기능이 없음 →Travis CI가 빌드한 결과물을 받아서 CodeDeploy가 가져갈 수 있도록 보관할 수 잇는 공간이 필요
- AWS 서비스에 외부 서비스는 접근할 수 없음 → 접근 가능한 권한을 가진 Key를 생성해서 사용 (IAM)

**IAM 유저 생성**

- 권한 추가
    - AmazonS3FullAccess
    - AWSCodeDeployFullAccess

**버킷 만들기**

- 모든 퍼블릭 액세스 차단

```yaml
language: java
jdk:
  - openjdk8

branches:
  only:
    - dev

# Travis CI 서버의 Homecache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.gradle'

script: "./gradlew clean build -x test"

# CI 실행 완료 시 메일로 알람notifications:
  email:
    recipients:
      - ******@gmail.com

before_deploy:
  - zip -r photo-tag-backend *
  - mkdir -p deploy
  - mv photo-tag-backend.zip deploy/photo-tag-backend.zip

deploy:
  - provider: s3
    access_key_id: $AWS_ACCESS_KEY #Travis repo setting에 설정된 값    secret_access_key: $AWS_SECRET_KEY
    bucket: buildzip-spring #s3 bucket    region: ap-northeast-2
    skip_cleanup: true
    acl: private #zip 파일 접근을 private으로    local_dir: deploy
    wait-until-deployed: true

```

- `before deploy`: deploy 명령어 실행되기 전에 수행
- CodeDeploy는 Jar 파일 인식 X → jar + 기타 설정 파일 모아서 압축
- `zip -r photo-tag-backend *` : 현재 위치의 모든 파일을 photo-tag-backend의 이름으로 압축
    - 명령어의 마지막 위치는 본인의 프로젝트 이름이어야 함
- `mkdir -p deploy` : deploy라는 디렉토리를 Travis CI가 실행중인 위치에서 생성
- `deploy` : S3로 파일 업로드 혹은 CodeDeploy로 배포 등 외부 서비스와 연동될 행위들을 선언
- `local_dir` : 해당 위치의 파일들만 S3로 전송

---

## AWS S3, CodeDeploy - Travis CI 연동

- * IAM 사용자와 역할의 차이 **
- 역할:
    - AWS 서비스에만 할당할 수 있는 구너한
    - EC2, CodeDeploy, SQS 등
- 사용자:
    - AWS 서비스 외에 사용할 수 있는 권한
    - 로컬 PC, IDC 서버 등

### 역할 만들기

- AWS 서비스 → EC2
- AmazonEC2RoleforAWS-CodeDeploy
- EC2 - IAM 역할 연결
    - 보안 > IAM 역할 수정
- 인스턴스 재부팅
- 재부팅 후 EC2 접속

```bash
aws s3 cp s3://aws-codedeploy-ap-northeast-2/latest/install . --region ap-northeast-2

```

```bash
chmod +x ./install
sudo ./install auto
sudo service codedeploy-agent status //agent 잘 실행되고 있는지 상태 검사

```
- CodeDeploy → EC2 접근하려면 권한 필요, 역할 생성
- IAM - 역할: AWS 서비스 - CodeDeploy

### CodeDeploy 생성

- AWS 배포
    - Code Commit
        - 깃헙 같은 코드 저장소
        - 프라이빗 기능 지원 but 이미 깃헙에서 다 무료로 지원하는 것들 → 잘 사용 X
    - Code Build
        - Travis CI 같은 빌드용 서비스
        - 멀티 모듈을 배포해야 하는 경우 사용해볼만 하지만 보통 젠킨스/팀시티 사용
    - CodeDeploy
        - AWS 배포 서비스
        - 대체재가 없음 → 많이 사용
        - 오토 스케일링 그룹 배포, 블루 그린 배포, EC2 단독 배포 등 기능 제공
- 어플리케이션 생성
- 배포 그룹 생성
- 서비스 역할 → 생성한 CodeDeploy용 IAM 역할 선택
- 배포 유형: 현재위치 선택
    - 블루/그린: 배포할 서비스가 2대 이상일 때
- 배포 구성: 한 번 배포할 때 몇 대의 서버에 배포할 지 결정
    - 1대니까 한 번에
- 로드 밸런서 비활성
- * Travis CI - S3 - CodeDeploy 연동**
- Travis CI 빌드 ⇒ S3에 zip 파일 전송 ⇒ `/home/ec2-user/build/zip` 으로 복사되어 압축 풀기
- 설정 파일 `appspec.yml`

```yaml
version: 0.0
os: linux
files:
  - source: /
    destination: /home/ec2-user/build/zip
    overwrite: yes

```
- version: CodeDeploy 버전 의미
- source: CodeDeploy에서 전달해준 파일 중 destination으로 이동시킬 대상 지정, / : 전체 파일
- destination: 지정된 파일 받을 위치
- `.travis.yml`

```yaml
language: java
jdk:
  - openjdk8

branches:
  only:
    - dev

# Travis CI 서버의 Homecache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.gradle'

script: "./gradlew clean build -x test"

# CI 실행 완료 시 메일로 알람
notifications:
  email:
    recipients:
      - pcn021152@gmail.com

before_deploy:
  - zip -r photo-tag-backend *
  - mkdir -p deploy
  - mv photo-tag-backend.zip deploy/photo-tag-backend.zip

deploy:
  - provider: s3
    access_key_id: $AWS_ACCESS_KEY #Travis repo setting에 설정된 값    secret_access_key: $AWS_SECRET_KEY
    bucket: buildzip-spring #s3 bucket    region: ap-northeast-2
    skip_cleanup: true
    acl: private #zip 파일 접근을 private으로    local_dir: deploy
    wait-until-deployed: true
    on:
      all_branches: true

  - provider: codedeploy
    access_key_id: $AWS_ACCESS_KEY #Travis repo settings에 설정된 값    secret_access_key: $AWS_SECRET_KEY

    bucket: buildzip-spring
    key: photo-tag-backend.zip

    bundle_type: zip #압축 확장자    application: photo-tag-backend #등록한 CodeDeploy 애플리케이션    deployment_group: photo-tag-backend-group
    region: ap-northeast-2
    wait-until-deployed: true
    on:
      all_branches: true

```

---

## 배포 자동화 구성
> 참고 #24 
- **`deploy.sh` 파일 추가**
- 위치는 최상위 폴더 `scripts/deploy.sh`

```bash
#!/bin/bash

REPOSITORY=/home/ec2-user/app/photo-tag-backend
PROJECT_NAME=phog

echo "> Build 파일 복사"

cp $REPOSITORY/zip/build/libs/*.jar $REPOSITORY/jar/

echo "> 현재 구동 중인 애플리케이션 pid 확인"

CURRENT_PID=$(pgrep -fl ${PROJECT_NAME} | grep jar | awk '{print $1}')

echo "현재 구동 중인 애플리케이션 pid: $CURRENT_PID"

if [ -z "$CURRENT_PID" ]; thenecho "> 현재 구동중인 애플리케이션이 없으므로 종료하지 않습니다."
elseecho "> kill -15 $CURRENT_PID"
  kill -15 $CURRENT_PID
  sleep 5
fiecho "> 새 어플리케이션 배포"

JAR_NAME=$(ls -tr $REPOSITORY/jar/*.jar | tail -n 1)

echo "> JAR Name: $JAR_NAME"

echo "> JAR_NAME에 실행권한 추가"

chmod +x $JAR_NAME

echo "> $JAR_NAME 실행"

nohup java -jar -Dspring.profiles.active=deploy $JAR_NAME > $REPOSITORY/nohup.out 2>&1 &

```

- 현재 수행중인 애플리케이션 프로세스 ID 찾아서 실행 중이면 종료
- `chmod +x $JAR_NAME` jar 파일에 실행 권한을 부여하기 → nohup으로 실행할 수 있도록
- `nohup`
    - nohup 실행 시 CodeDeploy는 무한 대기

    ⇒ 해결하기 위해 `nohup.out` 파일을 표준 입출력용으로 별도로 사용해야 함

    - 이렇게 하지 않으면 `nohup.out` 파일이 생기지 않고 CodeDeploy 로그에 표준 입출력이 출력됨
- `appspec.yml` 파일 수정

```yaml
version: 0.0
os: linux
files:
  - source: /
    destination: /home/ec2-user/app/photo-tag-backend/zip/
    overwrite: yes

permissions:
  - object: /
    pattern: "**"
    owner: ec2-user
    group: ec2-user

hooks:
  ApplicationStart:
    - location: scripts/deploy.sh
      timeout: 60
      runas: ec2-user

```

- CodeDeploy에서 EC2 서버로 넘겨준 파일들을 모두 ec2-user 권한 부여
- `hooks`
    - ApplicationStart 단계에서 `[deploy.sh](http://deploy.sh)` 파일을 ec2-user 권한으로 실행하게 함

---

## CodeDeploy 로그 위치

- `/var/log/aws/codedeploy-agent`
- 오류 발생 시 확인
